site_name: "MemGPT API Reference"

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
  - Data Models: data_models.md
  - Client:
      #- Overview: index.md
      - RESTClient: client/rest_client.md
      - LocalClient: client/local_client.md
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          group_by_category: true
          show_category_heading: true

#site_name: "MemGPT API Reference"
#
#theme:
#  name: "material"
#  features:
#    - navigation.instant
#    - navigation.footer
#    - navigation.indexes
#    - navigation.sections
#    - navigation.tabs
#    - navigation.tabs.sticky
#    - navigation.top
#
#nav:
#  - Data Models: data_models.md
#  - Client: index.md
#plugins:
#- mkdocstrings
#  #  custom_templates: templates
#  #  default_handler: python
#  #  handlers:
#  #    python:
#  #      options:
#  #        show_source: false
#